# Ejemplo motor ingesta para datos en streaming - event-hubs

In [1]:
%run ./includes/famia_stream_generator.ipynb

In [2]:
from databricks.sdk.runtime import dbutils, spark

dbutils.library.restartPython()

In [3]:
import sys

sys.path.append("../src")

from motor_ingesta import MotorIngesta, ConfigLoader

In [4]:
from pathlib import Path


config = ConfigLoader.from_file((Path.cwd().parent / 'kafka-config.json'))

In [5]:
namespace = dbutils.secrets.get(scope="lakehouses-ucm", key="namespace")
connection_string = dbutils.secrets.get(scope="lakehouses-ucm", key="connection-string")

farmia_generator = FamiaStreamGenerator(namespace, connection_string)

In [6]:
current_catalog = spark.sql("SELECT current_catalog()").collect()[0][0]
schema = "default"
landing = "-"
volume_name = "_meta"
meta = f"/Volumes/{current_catalog}/{schema}/{volume_name}"


spark.sql(f"CREATE VOLUME IF NOT EXISTS {current_catalog}.{schema}.{volume_name}")

DataFrame[]

In [7]:
motor_ingesta = MotorIngesta(
    catalog=current_catalog,
    schema=schema,
    landing=landing,
    meta=meta,
)

## Ingesta de mensajes en forma de eventos JSON desde Kafka

### Generación de eventos

In [ ]:
farmia_generator.create_topic("sensors-json")
await farmia_generator.produce_events("json", "sensors-json", 50)

### Consumo de eventos con el motor de ingesta

In [8]:
config_json = config[:1]

print(config_json[0].model_dump_json(indent=2)[:500])

{
  "source": {
    "format": "event-hubs",
    "messages": "json",
    "options": {
      "includeHeaders": "true",
      "startingOffsets": "earliest"
    },
    "connection": {
      "bootstrap_servers": "mde-lakehouses.servicebus.windows.net:9093",
      "security_protocol": "SASL_SSL",
      "sasl_mechanism": "PLAIN",
      "password": {
        "scope": "lakehouses-ucm",
        "key": "connection-string"
      }
    },
    "schema_": "event_id string, event_ts string, session_id string, c

In [9]:
queries = motor_ingesta.ingest(config_json)

for query in queries:
    query.awaitTermination()
    print(f'Query "{query.name}" finalizada correctamente.')

Query "sensors_json_raw" finalizada correctamente.

In [10]:
%sql
SELECT COUNT(*) FROM default.sensors_json_raw;

DataFrame[count(1): bigint]

In [11]:
%sql
SELECT * FROM default.sensors_json_raw LIMIT 10;

DataFrame[_key: binary, _value: binary, _topic: string, _partition: int, _offset: bigint, _timestamp: timestamp, _timestampType: int, _headers: array<struct<key:string,value:binary>>, _ingested_at: timestamp, event_id: string, event_ts: string, session_id: string, customer_id: string, event_type: string, product_id: string, channel: string]

## Ingesta de mensajes en forma de eventos AVRO desde Kafka

### Generación de eventos

In [ ]:
farmia_generator.create_topic("sensors-avro")
await farmia_generator.produce_events("avro", "sensors-avro", 50)

### Consumo de eventos con el motor de ingesta

In [12]:
config_avro = config[1:]

print(config_avro[0].model_dump_json(indent=2)[:500])

{
  "source": {
    "format": "event-hubs",
    "messages": "avro",
    "options": {
      "includeHeaders": "true",
      "startingOffsets": "earliest"
    },
    "connection": {
      "bootstrap_servers": "mde-lakehouses.servicebus.windows.net:9093",
      "security_protocol": "SASL_SSL",
      "sasl_mechanism": "PLAIN",
      "password": {
        "scope": "lakehouses-ucm",
        "key": "connection-string"
      }
    },
    "schema_": "{\"type\":\"record\",\"name\":\"AppEvent\",\"fields\":

In [14]:
queries = motor_ingesta.ingest(config_avro)

for query in queries:
    query.awaitTermination()
    print(f'Query "{query.name}" finalizada correctamente.')

Query "sensors_avro_raw" finalizada correctamente.

In [15]:
%sql
SELECT COUNT(*) FROM default.sensors_avro_raw;

DataFrame[count(1): bigint]

In [16]:
%sql
SELECT * FROM default.sensors_avro_raw LIMIT 10;

DataFrame[_key: binary, _value: binary, _topic: string, _partition: int, _offset: bigint, _timestamp: timestamp, _timestampType: int, _headers: array<struct<key:string,value:binary>>, _ingested_at: timestamp, event_id: string, event_ts: string, session_id: string, customer_id: string, event_type: string, product_id: string, channel: string]